### ISSUE TITLE
System randomness

### ISSUE THREAD

**Issue by burdges** [debuggor/schnorrkel-java#1]
There is seemingly no system randomness used in https://github.com/debuggor/schnorrkel-java/blob/293529594ff547e25d5673e521e9c3738218c315/src/main/java/com/debuggor/schnorrkel/sign/SigningTranscript.java#L28 

It's secure without system randomness here because you only do simple signatures, but stuff like multi-sigs are not secure without system randomness.  We always use system randomness in schnorrkel because we do these other protocols that require it. 

It's not immediately critical, but just a warning if you implement more.

**Comment by debuggor** [comment]
The random number is added at the back; currently only supports ordinary single sign and verification;
When I have time, I will consider adapting multi-signature and other functions

https://github.com/debuggor/schnorrkel-java/blob/293529594ff547e25d5673e521e9c3738218c315/src/main/java/com/debuggor/schnorrkel/merlin/TranscriptRngBuilder.java#L33
