### ISSUE TITLE
what value of Constants.RISTRETTO_GENERATOR_TABLE?

### ISSUE THREAD

**Issue by liweiww123** [debuggor/schnorrkel-java#2]
what value of Constants.RISTRETTO_GENERATOR_TABLE?

**Comment by debuggor** [comment]
You can check this library for details [Curve25519 library](https://github.com/cryptography-cafe/curve25519-elisabeth/blob/597bf78f175b0c00a72af7413ba1817554ea6cee/src/main/java/cafe/cryptography/curve25519/Constants.java#L155)

**Comment by liweiww123** [comment]
@debuggor  got it, thanks
