### ISSUE TITLE
The generated address is incorrect

### ISSUE THREAD

**Issue by liweiww123** [debuggor/schnorrkel-java#3]
i want generated polkadot address.
privareKey : 0xd3d8015b804bcf9114a62038e203fc87c8d7658568dc2116b936a81a0eef99fd
right should be：14SWSpQQjSafs3zniZrDrbPx89iu1BbAi3vNA3gSuuiiC1FU
but result:44c8b1681419a6c32c1728c30eb9d976d62051d9a3ae443270acff468dad3275

what should i do?

Below was  my code:

 
    public static KeyPair generateKeyPairSR(String secret) {
        byte[] seeds = HexUtils.hexToBytes(secret);
        Sr25519 sr25519 = Sr25519.fromSecretSeed(seeds);
        PrivateKey privateKey = sr25519.getPrivateKey();
        PublicKey publicKey = sr25519.getPublicKey();
        return new KeyPair(secret, HexUtils.bytesToHex(publicKey.toPublicKey()));
    }

private static final RistrettoGeneratorTable ristrettoTable = Constants.RISTRETTO_GENERATOR_TABLE;

    public static Sr25519 fromSecretSeed(byte[] seed) {
        PrivateKey privateKey = new PrivateKey(seed, ExpansionMode.Ed25519);
        byte[] key = privateKey.getKey();
        RistrettoElement ristretto = ristrettoTable.multiply(Scalar.fromBits(key));
        PublicKey publicKey = new PublicKey(ristretto);
        return new Sr25519(publicKey, privateKey);
    }

**Comment by debuggor** [comment]
This can only generate public and private key pairs. You can refer to this library to generate addresses from the public key[polkadot-java](https://github.com/polkadot-java/api)
